In [1]:
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
import scipy as sp 
import pandas as pd 

In [7]:
#implement matix multiplication 
#dot(a,b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

#2x2 matrix 

def mult(a,b): 
    result = [[0,0], 
             [0,0]]
    for i in range(len(a)): #iterate over rows of a 
        for j in range(len(b[0])): #iterate over cols of b
            #multiply rows and cols and iterate over rows of b 
            
            for k in range(len(b)): 
                result[i][j] += a[i][k] * b[k][j]
    return result 


In [56]:
#implementing logistic regression

x = [1,4,9,3,6,2]
y = [1,0,1]
x = np.asarray(x).reshape(-1,2)
y = np.asarray(y).reshape(3,1)


In [57]:
#define parameter array, shape(d,1)
#do without bias 
x = np.c_[np.ones((x.shape[0], 1)), x]

w = np.zeros((x.shape[1],1))


In [58]:
1/ (1+ np.exp(-np.dot(w.T,x)))

array([[0.5, 0.5, 0.5]])

In [59]:
#define sigmoid
def sigmoid(x,w): 
    y_hat = 1/ (1+ np.exp(-np.dot(w.T,x)))
    y_hat = y_hat.reshape(-1,1)
    return y_hat

In [62]:
#calculate optimal parameters: 
#loss function = -sum(ylog(y_hat) + (1-y)log(1-y_hat))
def gradient_loss(x,w,y): 
    m = x.shape[0]
    y_hat = sigmoid(x,w)
    grad = 1/m * np.dot(x.T,(y_hat - y))
    return grad

In [63]:
def sgd(alpha, y,x,w,num_iter):

    for i in range(num_iter +1): 
        grad = gradient_loss(x,w,y)
        w = w - alpha*grad 
    return w
        

In [66]:
w = sgd(0.01,y,x,w,10000)

In [68]:
bias = w[0][0]
bias

2.0196695622540553

In [69]:
y_hat = sigmoid(x,w)

In [70]:
y_hat

array([[0.97832397],
       [0.00960552],
       [0.99715743]])

In [79]:
def loss(y_hat,y): 
    return -1/x.shape[0] * (y*np.log(y_hat))

In [91]:
#predict on new values 
x_new = np.asarray([1,2,5,3,4,5]).reshape(-1,2)
y_new = [1,1,0]
x_new = np.c_[np.ones((x_new.shape[0], 1)), x_new]

In [92]:
sigmoid(x_new,w)

array([[0.97832397],
       [0.96710924],
       [1.        ]])

In [95]:
def accuracy(x, actual_classes, probab_threshold=0.5):
    predicted_classes = (sigmoid(x,w) >= 
                         probab_threshold).astype(int)
    predicted_classes = predicted_classes.flatten()
    accuracy = np.mean(predicted_classes == actual_classes)
    return accuracy * 100,predicted_classes

In [96]:
accuracy(x_new,y_new)

(66.66666666666666, array([1, 1, 1]))